### ISSUE TITLE
Management of Tokens authorization on Payment request and Merchant functions

### ISSUE THREAD

**Issue by Alexterieur0** [Paymium/api-documentation#30]
- Bugs on Tokens OAuth authorization, the option to interact with the merchant function does not appear at the creation of the API token on the platform. We need to add the option, the name is merchant something.

- We cannot tick the box payment request at the creation of API token on the platform. Must add the option.

**Comment by rishabhRsinghvi** [comment]
@Alexterieur0 Is this still late?

**Comment by jeromedcpaymium** [comment]
Thanks, fixed from a while.
