### ISSUE TITLE
"List orders" endpoint does not respect query parameters

### ISSUE THREAD

**Issue by aplusm** [Paymium/api-documentation#55]
According to the documentation, the endpoint /user/orders has the following query parameters: 

```
- offset
- limit 
- types
- active
```
When calling this endpoint in python:

- `active` does nothing. All orders are returned
- `types` is not taken into account (all order types are returned)
- `limit` does not work 
- `offset` seems respected though

Furthemore, how are orders ordered ?

**Comment by bguina** [comment]
bump - this endpoint is unusable.
`https://paymium.com/api/v1/user/orders?limit=10` -> 20 orders
`https://paymium.com/api/v1/user/orders?offset=0` -> 11 orders
`https://paymium.com/api/v1/user/orders?offset=11` -> 1 order
`https://paymium.com/api/v1/user/orders?offset=-9` -> HTTP 500

**Comment by jeromedcpaymium** [comment]
Thank you for your feedback. We have updated the API to clarify this point. 

see https://paymium.github.io/api-documentation/#tag/Order/operation/get-orders
